# -*- coding: utf-8 -*-
'''
CREATED 25-MAR-2021

DESCRIPTION: CONTAINS LIST OF COMMON PARAMETERS
NOTE: ALL PARAMETER NAMES SHOULD BE IN UPPERCASE

FORMAT:
PARAMETER_NAME = PARAMTER_VALUE

'''

# AWS parameter
AWS_ACCESS_KEY = "AKIATDYG75K5MJZJYVMY"
AWS_ACCESS_SECRET_KEY = "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"
# Project s3 main bucket
PROJECT_BUCKET = "testbucketai"
# app folder structure
ROOT_DIR = './app'



